### ISSUE TITLE
Фидбек по реализации

### ISSUE THREAD

**Issue by borNfreee** [php-cources/php-oop-file-converter-IliaTish#1]
Привет,

задание выполнено неплохо, особенно учитывая что ты первый. Ниже ряд замечаний/рекомендаций по коду.

1. Container - то, что ты знаешь о таком понятии, похвально. Однако здесь его применение не совсем корректное.

- BaseConverter. Во-первых, инжектить *весь* контейнер - это плохая практика. Так делать нельзя. Надо инжектить конкретные зависимости, чтобы бы было понятно от чего зависит твой класс. Во-вторых, у тебя инъекция и в конструкторе, и в сеттере. Зачем?

2. FileAnalyzer - избыточный класс. У `\SplFileObject` есть [нужный](http://php.net/manual/ru/splfileinfo.getextension.php) метод

3. BaseConverter - `$config = $this->container->get("JsonConfig");` - зачем эта строка? переменная далее не используется

4. FileWriter::writeToFile - избыточное именование метода. FileWriter::write() будет достаточно, ведь из название FileWriter понятно, что он пишет в файл.

5. Работа с CSV. Самописное решение не подходит, и непонятно что это такое `trim($csv,"\t\n\r\0\x0");`. Есть функции fputcsv/fgetcsv, Есть функционал для работы с CSV у класса \SplFileObject. Своё писать не стоит

6. Тесты на Unix не проходят, ошибка 

```diff
1) FileConverter\Tests\ConverterTest::test_it_converts_csv_file_to_csv
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 #Warning: Strings contain different line endings!
-'a,b,c
+'a,b,c
```

7. `htmlspecialchars("$value")` - нет смысла передавать переменную в кавычках, просто передай ее саму

8. Именование папок

- Interfaces - слишком общее имя, которе очень скоро превратиться в свалку. Интерфейсы должны лежать в своих папках, где они нужны, а не все вместе. Например интерфейс Reader должен лежать в папке Reader вместе с реализациями, и т.д.

9. Если предполагается только 1 реализация класса, то интерфейс создавать для такого класса не нужно. В твоем примере это Parser, на сколько я понимаю другой реализации парсера быть не может.

--------

Двигаешься в верном направлении, но замечания постарайся исправить.

**Comment by IliaTish** [comment]
Привет, исправил некоторые пункты, container еще не убрал, думаю как правильно его заменить.
Теперь я использую функции для работы с csv, но последний тест не проходит:
```phpunit
FileConverter\Tests\ConverterTest::test_it_converts_csv_file_to_csv
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 #Warning: Strings contain different line endings!
-'a,b,c
-d,e,f
+'a,b,c
+d,e,f

**Comment by borNfreee** [comment]
Контейнер убирать не обязательно, важно не инжектить его весь в конструктор. Инжектить надо конкретные зависимости (классы).

По поводу теста - ты на windows?

**Comment by IliaTish** [comment]
Да, я пока что на windows. Мне обязательно инжектить какой-то класс в Converter? Виталик подсказал мне инжектить Factory, только я не совсем понимаю, зачем это нужно. По сути фабрика у нас будет одна, которая создает мне определенные форматы по расширению.

**Comment by borNfreee** [comment]
> Мне обязательно инжектить какой-то класс в Converter?

Идея с инъекцией в том, что ты должен инжектить не весь контейнер, который содержит не пойми что, а конкретную зависимость для твоего класса.

т.е. вместо этого

```php
class BaseConverter implements Converter
{
    private $container;
    public function __construct(DependencyContainer $container)
    {
        $this->container = $container;
    }
    public function convert(\SplFileObject $file, string $outputFormat, string $outputFilePath): void
    {
        $factory = $this->container->get("FormatFactory");
    }
}
```

ты пишешь это

```php
class BaseConverter implements Converter
{
    private $factory;
    public function __construct(Factory $factory)
    {
        $this->factory = $factory;
    }
    public function convert(\SplFileObject $file, string $outputFormat, string $outputFilePath): void
    {
        $format = $this->factory->createFormat($extension);
        $newFormat = $this->factory->createFormat($outputFormat);
        $data = $format->parseFromFile($file);
        $newFormat->parseToFile($newFile,$data);
    }
}

```

**Comment by IliaTish** [comment]
Спасибо большое, я разобрался. Исправлю класс конвертера и фабрики. Остальные ошибки я исправил?

**Comment by borNfreee** [comment]
Теперь выглядит очень хорошо. Задание считаю успешно выполненным.
Маленькие ньюансы, принять во внимание на будущее (исправлять уже не надо).

1. `$xml_user_info`, `$xmlHandler` - разные стиль именования переменных. Надо консистентно выбрать 1 стиль
2. в описании контейнера у тебя есть классы, которых в реальности не существует (BaseParser например) - мертвый код
3. `htmlspecialchars("$value")` - подобные места еще остались, где переменная передается в кавычках. В этом нет смысла.

За кастомный класс ошибки - 👍

Удали пожалуйста репозиторий, если на это есть у тебя права, чтобы другие не подсматривали

**Comment by IliaTish** [comment]
Спасибо) Удалить не смогу, скорее всего, ты как создатель организации сможешь удалить.
